# ---- 输入变量 ----
let debug = true
let env = "prod"
let max_conn = 100

# ---- 块定义 ----
block frontend when env == "prod" 且 非 debug {
    block nginx when block frontend {
    }
    block static when debug 或 block nginx {
    }
}

block backend when (env == "prod" 且 max_conn >= 100) 或 debug {
    block api when block backend 且 block db {
    }
}

block db when env == "prod" {
}

block cache when debug {
}
